name: GitHub Actions Secrets
run-name: ${{ github.actor }} is testing out GitHub Secrets
on: [push]
jobs:
  Explore-GitHub-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        env:
          # This is soon secret host.
          ENV_FEA_TO_DEV: ${{ secrets.SECRET_FEA_TO_DEV }}
          ENV_DEV_TO_REL: ${{ secrets.SECRET_DEV_TO_REL }}
          ENV_REL_TO_PRD: ${{ secrets.SECRET_REL_TO_PRD }}
        # run: echo "My secret is ${ ENV_FEA_TO_DEV }" | sed 's/./& /g'
        run: |
          echo "secrets.SECRET_FEA_TO_DEV is ${{ secrets.SECRET_FEA_TO_DEV }}" | sed 's/./& /g'
          echo "secrets.SECRET_DEV_TO_REL is ${{ secrets.SECRET_DEV_TO_REL }}" | sed 's/./& /g'
          echo "secrets.SECRET_REL_TO_PRD is ${{ secrets.SECRET_REL_TO_PRD }}" | sed 's/./& /g'

